spring.application.name=restful-web-services

server.port=8081

logging.level.org.springframework=info
management.endpoints.web.exposure.include=*

spring.h2.console.enabled=true

spring.jpa.show-sql=true

spring.security.user.name=user
spring.security.user.password=qwerty123

spring.datasource.url=jdbc:mysql://localhost:3307/social-media-database
spring.datasource.username=social-media-user
spring.datasource.password=dummypassword

#based on the @entity, whenever application run the schema will auto updated
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.datasource.url=jdbc:h2:mem:Test1db
spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=create


#spring.mvc.apiversion.use.path-segment=0
#spring.mvc.apiversion.use.query-parameter=version
#spring.mvc.apiversion.use.header=X-API-VERSION
#Accept:application/json;version=2
#spring.mvc.apiversion.use.media-type-parameter[application/json]=version
